#!/usr/bin/env Rscript
# RQ3 -- historical non-identified diagnostics and the detection model.
#
# Two quantities, each reported with the reason it is not the answer:
#
# (a) A historical Chapman calculation on aggregate death counts. It is kept to
#     reproduce earlier outputs but is PROHIBITED as an estimate or bound: the
#     overlap is assumed with pmin(), not observed by person-level linkage.
#
# (b) A detection model: P(a municipality reports at least one confirmed case
#     in a year) as a function of population, state notification effort and
#     region, used to ask how many cases the country would have measured if
#     every state notified like the states that notify most. Reported as a
#     RANGE over the choice of reference, because that choice is the estimate.
#
# Long fits run through bounded_call() in a child process with an explicit
# budget: an in-process time limit is not observed by compiled code, and this
# harness has already lost a night to that. Everything the child needs is
# reconstructed inside the child; nothing is closed over.
#
# Usage: Rscript studies/leptospirosis/20_rq3_ascertainment.R

suppressWarnings(source("renv/activate.R"))
suppressPackageStartupMessages({
  library(data.table); library(arrow)
})
for (f in c("06_ascertainment.R", "09_exec.R")) source(file.path("R", f))
if (!exists(".need")) {
  .need <- function(pkg) if (!requireNamespace(pkg, quietly = TRUE))
    stop("package required: ", pkg, call. = FALSE)
}

PANEL <- "data/panel/triangulation_municipality_year.parquet"
EFFORT <- "data/results/rq3_ascertainment/01_state_surveillance.csv"
OUT <- "data/results/rq3_ascertainment"
dir.create(OUT, showWarnings = FALSE, recursive = TRUE)
SEED <- 20260731L

stopifnot(file.exists(PANEL))
tri <- as.data.table(arrow::read_parquet(PANEL))
message(sprintf("panel: %d rows, %d municipalities, years %d-%d",
                nrow(tri), uniqueN(tri$munic_code), min(tri$year), max(tri$year)))

sim_years <- sort(unique(tri[sim_covered == TRUE, year]))
sih_years <- sort(unique(tri[sih_covered == TRUE, year]))
has_sih <- length(sih_years) > 0
message(sprintf("windows: SIM %d-%d | SIH %s",
                min(sim_years), max(sim_years),
                if (has_sih) sprintf("%d-%d", min(sih_years), max(sih_years))
                else "ABSENT"))

# ===========================================================================
# (a) Non-identified historical Chapman calculation on the death numerator
# ===========================================================================
#
# The two lists are SINAN deaths (a notified case whose outcome was recorded as
# death) and SIM A27 deaths (a death certificate whose underlying cause is
# A27). They are generated by different people through different pathways,
# which is the only reason this is worth attempting at all.
#
# Three assumptions and how each fails HERE:
#
# 1. Independence. Violated, positively. A leptospirosis death that was
#    notified is much more likely to have "leptospirose" written on the death
#    certificate, because the same clinical team writes both. Positive
#    dependence inflates the overlap, which deflates N_hat. Downward bias.
#
# 2. Perfect linkage. NOT SATISFIED AT ALL. We have no record linkage. The
#    overlap used here is a municipality-year CO-OCCURRENCE PROXY: within a
#    municipality-year that has both SINAN deaths and SIM A27 deaths, the
#    overlap is taken as the smaller of the two counts. That is the MAXIMUM
#    possible overlap, so it produces the SMALLEST possible N_hat. Downward
#    bias, deliberately, so that the result can only be an underestimate.
#
# 3. Homogeneous catchability. Violated: a death in a large municipality with a
#    referral hospital enters both lists; a death at home in a small one enters
#    neither. Downward bias again.
#
# These observations do not rescue identification. An assumed aggregate overlap
# is not a capture history; the numbers below are diagnostics retained for
# provenance and MUST NOT be reported as estimates or bounds.

cr_input <- tri[year %in% sim_years,
                .(munic_code, uf_abbr, region, year,
                  sinan_deaths = as.numeric(sinan_deaths),
                  sim_deaths   = as.numeric(sim_a27_deaths))]
cr_input[, overlap_proxy := pmin(sinan_deaths, sim_deaths)]

cr_caveats <- c(
  "Overlap is a municipality-year CO-OCCURRENCE PROXY (pmin of the two counts), not a record linkage.",
  "PROHIBITED FOR INFERENCE: pmin is an assumed overlap, so Chapman N_hat is neither an estimate nor a formal lower bound.",
  "Both lists over-sample deaths that reached a hospital; the at-home death reservoir is invisible to this design.")

cr_national <- capture_recapture(
  cr_input, by = character(),
  sources = c(n1 = "sinan_deaths", n2 = "sim_deaths", m = "overlap_proxy"),
  caveats = cr_caveats)
cr_year <- capture_recapture(
  cr_input, by = "year",
  sources = c(n1 = "sinan_deaths", n2 = "sim_deaths", m = "overlap_proxy"),
  caveats = cr_caveats)
cr_state <- capture_recapture(
  cr_input, by = "uf_abbr",
  sources = c(n1 = "sinan_deaths", n2 = "sim_deaths", m = "overlap_proxy"),
  caveats = cr_caveats)

# A second, looser overlap definition: count a municipality-year as
# contributing 1 to the overlap if BOTH systems recorded at least one death
# there. This is the minimum defensible overlap given that both systems saw the
# same place in the same year, and therefore gives the LARGEST N_hat this
# calculation produces. Reporting both only exposes sensitivity to an
# unidentified overlap assumption; it does not create an identified interval.
cr_input[, overlap_min := as.numeric(sinan_deaths > 0 & sim_deaths > 0)]
cr_national_loose <- capture_recapture(
  cr_input, by = character(),
  sources = c(n1 = "sinan_deaths", n2 = "sim_deaths", m = "overlap_min"),
  caveats = c(cr_caveats,
              "This variant sets the overlap to 1 per co-occurring municipality-year, the smallest defensible overlap; it bounds the estimator from above."))

cat("\n=== (a) NON-IDENTIFIED HISTORICAL CHAPMAN DIAGNOSTIC -- DO NOT REPORT,",
    min(sim_years), "-", max(sim_years), "===\n")
print(cr_national)
cat("\nupper-variant (overlap = 1 per co-occurring municipality-year):\n")
print(cr_national_loose)
cat("\nCAVEATS:\n"); cat(paste0("  - ", attr(cr_national, "brepi_cr_caveats"),
                                collapse = "\n"), "\n")

fwrite(cr_national, file.path(OUT, "10_cr_deaths_national.csv"))
fwrite(cr_national_loose, file.path(OUT, "10b_cr_deaths_national_loose.csv"))
fwrite(cr_year, file.path(OUT, "11_cr_deaths_by_year.csv"))
fwrite(cr_state[order(-N_hat)], file.path(OUT, "12_cr_deaths_by_state.csv"))
cat("\n--- by state (top 12 by N_hat) ---\n")
print(head(cr_state[order(-N_hat)], 12))

# ===========================================================================
# (b) Detection model
# ===========================================================================
#
# Outcome: does municipality i report at least one confirmed case in year t?
# Predictors: log10 population (the size gradient), the state's notification
# RATE (suspicions raised per 100k per year -- a property of the surveillance
# system, not of the pathogen), macro-region, and year.
#
# The identifying assumption is stated plainly: state notification effort
# affects DETECTION and not TRANSMISSION. It is not testable here. It is
# defensible because notification effort is set by state health secretariats
# and their case-definition and laboratory policies, and implausible that a
# secretariat's paperwork intensity changes the number of Leptospira in the
# floodwater. Where it fails -- a state that notifies more because it genuinely
# has more disease -- the model attributes real burden to detection and
# OVERSTATES under-ascertainment. That is the direction of the main risk and it
# is why the answer is reported as a range and never as a point.

effort <- fread(EFFORT)[, .(uf_abbr, notif_rate, confirm_ratio, lab_share)]
mdl <- merge(tri[, .(munic_code, uf_abbr, region, year,
                     population = as.numeric(population),
                     cases = as.numeric(sinan_confirmed))],
             effort, by = "uf_abbr", all.x = TRUE)
mdl <- mdl[is.finite(population) & population > 0]
mdl[, `:=`(reported = as.integer(cases > 0),
           log_pop = log10(population),
           log_effort = log(notif_rate),
           region = factor(region),
           yearf = factor(year))]
stopifnot(!any(is.na(mdl$log_effort)))
message(sprintf("detection model rows: %d (%.1f%% report a case)",
                nrow(mdl), 100 * mean(mdl$reported)))
saveRDS(mdl, file.path(OUT, "_detection_input.rds"))

fit_detection <- function(path, out) {
  suppressPackageStartupMessages({ library(data.table); library(MASS) })
  d <- readRDS(path)
  # (i) detection probability
  det <- glm(reported ~ log_pop + log_effort + region + yearf,
             family = binomial(), data = d)
  # (ii) measured-case intensity, negative binomial with a population offset.
  #      The elasticity of measured incidence to notification effort is the
  #      quantity of interest: under complete ascertainment it is 0.
  cnt <- MASS::glm.nb(cases ~ log_effort + log_pop + region + yearf +
                        offset(log(population)), data = d)
  list(det_coef = summary(det)$coefficients,
       cnt_coef = summary(cnt)$coefficients,
       theta = cnt$theta,
       det_aic = AIC(det), cnt_aic = AIC(cnt),
       # Counterfactual: raise every state's notification effort to a reference
       # quantile of the observed state distribution, hold everything else.
       counterfactual = local({
         qs <- c(0.50, 0.75, 0.90, 1.00)
         ref <- quantile(unique(d[, .(uf_abbr, notif_rate)])$notif_rate, qs)
         obs_cases <- sum(d$cases)
         obs_reporting <- mean(predict(det, type = "response"))
         rbindlist(lapply(seq_along(qs), function(k) {
           d2 <- copy(d)
           d2[, log_effort := log(pmax(notif_rate, ref[k]))]
           data.table(
             reference_quantile = qs[k],
             reference_notif_rate = as.numeric(ref[k]),
             observed_cases = obs_cases,
             expected_cases = sum(predict(cnt, newdata = d2, type = "response")),
             observed_reporting_prob = obs_reporting,
             expected_reporting_prob = mean(predict(det, newdata = d2,
                                                    type = "response")))
         }))
       }))
}

budget <- limits(wall_seconds = 1800, max_rss_mb = 12000, poll_seconds = 2)
run <- bounded_call(
  fit_detection,
  args = list(path = file.path(OUT, "_detection_input.rds"), out = OUT),
  budget = budget, packages = character(), label = "rq3_detection")
print(run)

if (run$status != "ok") {
  cat("\nDETECTION MODEL DID NOT COMPLETE:", run$status, "-", run$error, "\n")
  cat("Reported as unavailable. It is not replaced by an unbounded rerun.\n")
} else {
  v <- run$value
  cat("\n=== (b) DETECTION MODEL ===\n")
  cat("\nP(reports >= 1 confirmed case in the year) -- logistic\n")
  print(round(v$det_coef[c("(Intercept)", "log_pop", "log_effort"), ], 4))
  cat("\nMeasured-case intensity -- negative binomial, offset log(population)\n")
  print(round(v$cnt_coef[c("(Intercept)", "log_effort", "log_pop"), ], 4))
  cat(sprintf("\nelasticity of measured incidence to state notification effort: %.3f\n",
              v$cnt_coef["log_effort", "Estimate"]))
  cat("  (0 would mean detection is complete: you find the same disease however hard you look)\n")
  cat("\nCounterfactual: every state notifies at least at the reference rate\n")
  cf <- as.data.table(v$counterfactual)
  cf[, ratio := expected_cases / observed_cases]
  print(cf[, .(reference_quantile, reference_notif_rate,
               observed_cases = round(observed_cases),
               expected_cases = round(expected_cases),
               ratio = round(ratio, 2),
               observed_reporting_prob = round(observed_reporting_prob, 3),
               expected_reporting_prob = round(expected_reporting_prob, 3))])
  fwrite(cf, file.path(OUT, "13_detection_counterfactual.csv"))
  fwrite(as.data.table(v$det_coef, keep.rownames = "term"),
         file.path(OUT, "14_detection_logistic_coefficients.csv"))
  fwrite(as.data.table(v$cnt_coef, keep.rownames = "term"),
         file.path(OUT, "15_intensity_nb_coefficients.csv"))

  cat("\nASSUMPTIONS behind the range above:\n")
  cat("  1. State notification effort acts on detection, not on transmission.\n")
  cat("     If a high-notifying state also genuinely has more disease, this\n")
  cat("     OVERSTATES under-ascertainment.\n")
  cat("  2. The reference state is treated as ascertainment-complete. It is not:\n")
  cat("     even Acre misses the mild and subclinical reservoir entirely, so the\n")
  cat("     ratio is a LOWER bound on total infection under-ascertainment while\n")
  cat("     being an UPPER bound under assumption 1. The two errors point in\n")
  cat("     opposite directions and are not netted out here.\n")
  cat("  3. Region and year absorb genuine geographic and epidemic variation.\n")
  cat("     Effort is measured at STATE level, so within-state detection\n")
  cat("     heterogeneity -- which the silence gradient says is large -- is\n")
  cat("     absorbed into the population term.\n")
}

# ===========================================================================
# (c) Map-ready surveillance completeness table
# ===========================================================================
win <- if (has_sih) intersect(sim_years, sih_years) else sim_years
m <- tri[year %in% win, .(
  years = uniqueN(year),
  pop = mean(population, na.rm = TRUE),
  sinan_confirmed = sum(sinan_confirmed, na.rm = TRUE),
  sinan_deaths = sum(sinan_deaths, na.rm = TRUE),
  sim_a27_deaths = sum(sim_a27_deaths, na.rm = TRUE),
  sih_a27_admissions = if (has_sih) sum(sih_a27_admissions, na.rm = TRUE) else NA_real_
), by = .(munic_code, name, uf_abbr, region)]

m[, `:=`(
  sinan_positive = sinan_confirmed > 0,
  other_positive = (sim_a27_deaths > 0) |
    (if (has_sih) sih_a27_admissions > 0 else FALSE))]
m[, surveillance_class := fcase(
  sinan_positive & other_positive, "corroborated",
  sinan_positive & !other_positive, "SINAN only",
  !sinan_positive & other_positive, "cross-system discordant",
  default = "unobserved in all three")]
# The completeness ratio compares what SINAN measured against what the
# independent systems imply it should have seen. It is defined only where an
# independent signal exists; elsewhere it is NA, not 1.
m[, sinan_per_independent_signal := fifelse(
  other_positive,
  sinan_confirmed / (sim_a27_deaths + fifelse(is.na(sih_a27_admissions), 0,
                                              sih_a27_admissions)),
  NA_real_)]
fwrite(m[order(surveillance_class, -pop)],
       file.path(OUT, "16_surveillance_completeness_map.csv"))
cat("\n=== (c) SURVEILLANCE COMPLETENESS, municipality classes ===\n")
print(m[, .(municipalities = .N, population = round(sum(pop)),
            sinan_cases = sum(sinan_confirmed),
            sim_deaths = sum(sim_a27_deaths),
            sih_admissions = sum(sih_a27_admissions)),
        by = surveillance_class][order(-municipalities)])

assert_no_strays(kill = TRUE)
cat("\nwrote RQ3 model outputs to", OUT, "\n")
